title: "A Daily Dose of History"
description: "Chronicles of the Past, Delivered Daily"
baseurl: ""
url: "https://adailydoseofhistory.github.io"
author: "The Chronicler"
email: "indianart3103@gmail.com"
adsense_publisher_id: "ca-pub-6777857056104326"

markdown: kramdown
permalink: /posts/:title/

plugins:
  - jekyll-feed
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
